//
//  NSObject+WWModel.h
//  Coding
//
//  Created by WitChan on 16/8/30.
//  Copyright © 2016年 WitChan.com. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface NSObject (WWModel)

+ (instancetype)modelWithDictionary:(NSDictionary *)dictionary;
- (NSArray *)propertyList;

@end
